### ISSUE TITLE
How to reconnect automatically

### ISSUE THREAD

**Issue by kellertobias** [Sofie-Automation/sofie-atem-connection#100]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[X] question about how to use this project

* **Summary**

I am writing an automation using this library, and need a way to automatically reconnect. There might be a case where there happens one of the following:
- Server is started before ATEM
- ATEM is rebooted
- ATEM or server looses Network Connection

I need to make sure that the connection is automatically established (not only on server start). What would be the best pattern to do this?

**Comment by mint-dewit** [comment]
Reconnecting is done automatically inside the library, you can listen to the `disconnected` and `connected` events for updates as is done here for example: https://github.com/nrkno/tv-automation-state-timeline-resolver/blob/16988406136d15dbd0097202c3e30cba2614ea61/src/devices/atem.ts#L100

**Comment by tcgerhard** [comment]
Note that a message "reconnect" will be logged whenever the library notes a disconnect and tries to initiate a reconnect.

`atemSocketChild.js:            this.log('reconnect');`
