### ISSUE TITLE
Multiview "View Control" Quadrant splitting

### ISSUE THREAD

**Issue by iamjohnbarker** [Sofie-Automation/sofie-atem-connection#109]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
I am really keen to take advantage of this module in a project I am working on, and for that, I would love to see the addition of the "View Control" multiview option within the ATEM. This allows the user (on some ATEM models) to split the multiview into up-to 16 quadrants or down to 4 quadrants.

I see that LibAtem already mentions the "SupportsQuadrants" boolean which might be a great start. I would give this a go myself but I am super unsure about Typescript and I not really sure where to start to add it!

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
I'll be happy to talk through my apps use case more if needed, but as an overview, it is a clickable multiview running on a host machine where the user adds their multiview as a webcam, and a control layer sits over-top of that to cut the show - In addition, the ability to remap the multiview will be needed. This can be achieved through macros, but I know that will not be a sustainable approach!

**Comment by Julusian** [comment]
I have had someone else request this too, so it is highly likely to be done in the next couple of weeks.

**Comment by iamjohnbarker** [comment]
Wonderful - If I can be of any help then do let me know!

**Comment by Julusian** [comment]
This is part of #111

**Comment by Julusian** [comment]
This is now available in the `3.0.0-nightly-latest-20210530-132658-16c3cdd.0` beta build.
