### ISSUE TITLE
Send UpstreamKeyer A/B Keyframes?

### ISSUE THREAD

**Issue by chrisspiegl** [Sofie-Automation/sofie-atem-connection#114]
* **I'm submitting a ...**
[x] feature request (possibly)
[x] question about how to use this project

* **Summary**

I would like to set an upstream keyer keyframe and then fly to it… but from what I can find in the docs I can only tell the system to fly to a key (A/B/Full) but I have not yet found the option to actually send those keyframe details before flying there.

Am I missing something? Is this possible?

**Comment by endreszabo** [comment]
On Fri, May 14, 2021 at 00:48:17-0700, Chris Spiegl wrote:
> Am I missing something? Is this possible?
Most likely it's not implemented yet.

Right now, you can change the key position 'manually' but can not store them as a keyframe.

It is definitely possible and should not be hard to implement.

**Comment by chrisspiegl** [comment]
@endreszabo Thank you for your reply.
My program is indeed able to change the position via the `myAtem.setUpstreamKeyerDVESettings()` but I wanted to create flyKey transitions.
Maybe I will look into it at some point (or someone else can).
I have a hard time reading / understanding the underlying code in this library 🙈 working with bits and stuff is not my strength.

**Comment by Julusian** [comment]
Yeah, I have missed the keyframe commands when trying to get the keyer commands to be complete. I shall need to get that implemented as part of #111

**Comment by Julusian** [comment]
This is now available in the `3.0.0-nightly-latest-20210530-132658-16c3cdd.0` beta build.

**Comment by chrisspiegl** [comment]
@Julusian I have just tested this in my app and it worked like a charm.

One question: I did not see where and how to set the Keyframe Rate?
Am I missing something there?

Current workaround would be to call `setUpstreamKeyerDVESettings` before running the keyframe…

```js
myAtem.setUpstreamKeyerDVESettings({ rate: 10 })
```

But the `rate` could probably be added to `UpstreamKeyerFlyKeyframe`?

```js
export interface UpstreamKeyerFlyKeyframe extends Omit<UpstreamKeyerDVEBase, 'maskEnabled'> {
	readonly keyFrameId: number
	rate: number
}
```

Cheers

**Comment by Julusian** [comment]
`myAtem.setUpstreamKeyerDVESettings({ rate: 10 })` is the correct way to set the rate

Adding it to `UpstreamKeyerFlyKeyframe` wouldnt be correct, as the rate doesnt belong to the keyframe, it belongs to the dve.
Maybe it should be added to the `runUpstreamKeyerFlyKeyTo()` method as an optional parameter, but so far we have been keeping to one command per method

**Comment by chrisspiegl** [comment]
Ah, ok. That makes sense now. It is just visually so close to each other in ATEM Software Control that I thought it would make sense to send with the `UpstreamKeyerFlyKeyFrame`.

I understand the desire to keep the run command just as one command, but would also say that it would be a good addition to have the rate as an optional parameter there. I don't really have a hard opinion and both ways work I think.
