### ISSUE TITLE
Save startup state

### ISSUE THREAD

**Issue by hrueger** [Sofie-Automation/sofie-atem-connection#116]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

First of all, thanks for this excellent library. I've been using it for a few days now and it not only works perfectly but it also is very easy to use.
In the ATEM Software Control the current state can be saved as the Startup State. It would be great if this could also be done via this lib.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I'm using an ATEM Mini Pro, if that matters.

**Comment by Julusian** [comment]
This is now available in the `3.0.0-nightly-latest-20210530-132658-16c3cdd.0` beta build.
