### ISSUE TITLE
Control Fairlight Master Channel

### ISSUE THREAD

**Issue by hrueger** [Sofie-Automation/sofie-atem-connection#117]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

First of all, thanks for this excellent library. I've been using it for a few days now and it not only works perfectly but it also is very easy to use.
I'm using an ATEM Mini Pro which has the Fairlight Audio instead of the old one. Hoever, I could not find any methods to control the master channel. If I move it in the ATEM Software Control, the only path which I receive in the `stateChanged` event is `["info.lastTime"]`.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by Julusian** [comment]
This is now available in the `3.0.0-nightly-latest-20210530-132658-16c3cdd.0` beta build.
