### ISSUE TITLE
How to work with macros

### ISSUE THREAD

**Issue by br8kpoint** [Sofie-Automation/sofie-atem-connection#119]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ x] question about how to use this project

* **Summary**
Is there a good resource on how to use the library to work with macros?

Initially I'd like to just list the macros defined by name and then run them however that happens.

Then I'd like to be able to change the macros around. Do you do this by loading an xml or would it be programatically by setting the properties?

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I'm looking to add macro functionality to the touch portal extension I built: https://github.com/br8kpoint/touch-portal-atem

**Comment by Julusian** [comment]
Currently the support for macros matches what you can do in the atem software except for handling them in xml form. The methods available are:
![image](https://user-images.githubusercontent.com/1327476/121778598-7e05c000-cb8f-11eb-8213-8586fc618b83.png)

Being able to generate and upload macros is something I would like to support (and did make some progress on in the past for another atem library/project https://github.com/LibAtem/AtemMacroEditor), but I have not found any prior work on it, so it is a very large task of reverse engineering every macro operation (with no list of what they all are).

It is something I would like to do one day, but I need to find the time to get it started

**Comment by br8kpoint** [comment]
Thanks for the response. I finally have some time to work on this and can see the functions to actually run and control the macros. What I do not see is a way to actually obtain the list of macros already defined in the system. I would like to present the list of macros by name in the UI of my plugin for say the "Run" action of a Touch Portal button that users define. Is there a way to get the number of macros that are currently defined and then get the macro meta data such as the name/index? Something like macroGetProperties?

**Comment by Julusian** [comment]
Look at the `state` property on the client object. That tracks the current state of the atem, including the names and descriptions of the macros. Be careful to handle it and some of the contents being null
