### ISSUE TITLE
Remote Reboot

### ISSUE THREAD

**Issue by ghost** [Sofie-Automation/sofie-atem-connection#126]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

I've done a bit of research on this one, but I can't seem to find any definitive answers. Is there _any_ way to remotely reboot an ATEM Mini / Mini Pro etc without some sort of network connected PDU? Other than forcing a Firmware update (risky at the best of times, let alone remotely), I can't find any way to force a restart and for AV systems that we're supporting, this means having to get someone on the ground on the phone to dig around in racks to try and power-cycle things.

It's really frustrating and I'm sure there must be some command that can be sent for a reboot. If there is, and this library can implement that command, I would be insanely grateful.

**Comment by Julusian** [comment]
I have previously been through all the official sdk and did not see anything for rebooting an atem.
Additionally, as firmware updates require a manual power cycle of the device, that suggests it is not possible.

So unfortunately I don't think this is possible to do.

**Comment by ghost** [comment]
Hi @Julusian - that's OK, I thought that may be the case. I'd appreciate it if you could just keep this at the back of your mind for future changes should that option be added to the SDK. 

Other than that, many thanks for a great library.
