### ISSUE TITLE
Documentation Link

### ISSUE THREAD

**Issue by philliousfogg** [Sofie-Automation/sofie-atem-connection#128]
The documentation link is broken - can this be restored?

**Comment by Julusian** [comment]
The link has changed recently, but it should be updated everywhere (except for published packages) 
https://nrkno.github.io/sofie-atem-connection/

**Comment by philliousfogg** [comment]
Ah brilliant thank you – this is an excellent project thanks.

I don’t think the NPM link hasn’t been updated.

Kind Regards,

Phil Gorman

Creative Blast

Create|Control|Automate

Telephone: +44 (0) 747 331 4463
Email/Skype For Business: ***@***.******@***.***>






From: Julian Waller ***@***.***>
Reply to: nrkno/sofie-atem-connection ***@***.***>
Date: Thursday, 17 February 2022 at 22:07
To: nrkno/sofie-atem-connection ***@***.***>
Cc: Phil Gorman ***@***.***>, Author ***@***.***>
Subject: Re: [nrkno/sofie-atem-connection] Documentation Link (Issue #128)


The link has changed recently, but it should be updated everywhere (except for published packages)
https://nrkno.github.io/sofie-atem-connection/
