### ISSUE TITLE
Missing destroy/close functionality

### ISSUE THREAD

**Issue by haakonnessjoen** [Sofie-Automation/sofie-atem-connection#13]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
There is no way of stopping the module from retrying connections. So if you want to remove the connection, or disconnect. It will continue to try to reconnect, even after removing the reference to the module.

**Comment by mint-dewit** [comment]
Thanks for the report.

A disconnection method has been on todo list for a while but kept falling off. One of those easy tasks you just never get around to I guess. Anyway, I just pushed an update that adds a `disconnect()` method to the Atem class which should properly dispose of the socket and timers. Version `0.2.1` should be up on npm by now.

**Comment by haakonnessjoen** [comment]
Thanks for the insanely quick fix, seems to work great! :)

**Comment by jesperstarkar** [comment]
<3 Companion
