### ISSUE TITLE
AUX Problems on 2M/E

### ISSUE THREAD

**Issue by haakonnessjoen** [Sofie-Automation/sofie-atem-connection#14]
* **I'm submitting a ...**
[X] bug report

* **Summary**

We seem to have problems controlling more than 3 aux outputs. I do not have access to an atem with more than 3 auxes myself, but several users has reported that 4,5,6 does not work.

I am just using setAuxSource with auxbus 0-5. Are the indexes non-linear?

**Comment by mint-dewit** [comment]
Strange. I don't see any reason why that wouldn't work. Our command is the same as LibAtem, and I vaguely recall testing this with bus 6 on a 2 M/E (that I don't have access to anymore, unfortunately)

Are you able to provide wireshark traces perhaps? I'll try to get someone with a 2m/e to check as well.

**Comment by Julusian** [comment]
I am pretty sure we are using this with aux5 and aux6 of a 2ME4K without issue, but I shall try to double check it is still working.

Another thing to check is which version of the ATEM firmware is being used, just to check that isn't the issue even though that is unlikely to have an effect.

**Comment by mint-dewit** [comment]
> Another thing to check is which version of the ATEM firmware is being used, just to check that isn't the issue even though that is unlikely to have an effect.

The Skaarhoj lib actually uses a slightly different command structure it appears, so that could have an effect. We've developed this library against firmware version 7.2.

**Comment by Lange** [comment]
Just confirmed that `setAuxSource` works as expected on my 2 M/E 4K Production Studio. The indexes are indeed `0-5`.

**Comment by haakonnessjoen** [comment]
Would it be possible for you to try to download companion on https://bitfocus.io/companion/ and try changing aux with the ATEM support there? You don't need the stream deck device to test. I don't have access to a 2ME4k at the moment. :(

**Comment by Lange** [comment]
On my setup, Companion is only able to successfully change Aux 1. It fails to change Aux 2-6.

**Comment by Lange** [comment]
I have confirmed that Aux 1 is always the recipient of changes, regardless of which Aux is selected.

**Comment by Lange** [comment]
Issue found and fixed in the Companion app, submitting a PR shortly.

**Comment by Lange** [comment]
PR here: https://github.com/bitfocus/companion-module-atem/pull/1

Closing this issue, as it is not a problem in `atem-connection`.
