### ISSUE TITLE
Upload errors "Lost lock mid-transfer"

### ISSUE THREAD

**Issue by jzarl** [Sofie-Automation/sofie-atem-connection#143]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
   * We're using sofie-atem-connection to upload still images to an Atem constellation mixer from a RaspberryPi model 3B. This works well, allthough the upload time is rather significant, usually taking somewhere between 100 to 130 seconds for 30 images  in 1080p mode.
   * I thought that maybe switching to a RaspberryPi model 4B could improve upload times, and indeed it does. The same number of images now take at most 40 seconds to upload (when successful).
   * Unfortunately, with the newer model 4, I often get the error "Error: Lost lock mid-transfer", leading to failed uploads.
Is there anything I can do to troubleshoot the issue and find the root cause?

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
   * I'm using atem-connection 3.2.0 from the npm repository, and nodeJS v18.15.0.

**Comment by jzarl** [comment]
I found that simply retrying failed uploads works around the issue (if an upload failed it succeeds on the second attempt).

If there's anything to avoid running into the "Lost lock mid-transfer" error, I'm still quite interested, but otherwise it's ok for me if you close the issue...

**Comment by ianshade** [comment]
~~It seems like a bug related to the use of the ThreadedClass library. Setting `disableMultithreaded` to `true` seems to solve it for me, but of course it's just a workaround and I wouldn't recommend it unless your use case allows it.~~

**Comment by Julusian** [comment]
I believe this is fixed by #147 in v3.3.0

**Comment by jzarl** [comment]
Thank you - I can confirm that the issue indeed seems to be fixed.
