### ISSUE TITLE
Napi::Error crash (in dependency?)

### ISSUE THREAD

**Issue by hrueger** [Sofie-Automation/sofie-atem-connection#151]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Disclaimer: I don't think this is a direct issue with this library, however, I'm trying to understand what's happening here and need some info.
I'm running my application bundled using `vercel/pkg` on a Pi 4 running the 64-bit Pi OS, therefore `arm64`. When I import and instanciate this lib, my process crashes after a few seconds with this error:
```
Aug 19 08:48:48 glue start-glue[546]: terminate called after throwing an instance of 'Napi::Error'
Aug 19 08:48:48 glue start-glue[546]:   what():
Aug 19 08:48:48 glue start-glue[504]: /bin/start-glue: line 9:   546 Aborted                 /bin/glue --http-port 80 --logfile /var/log/glue.log --data /var/lib
Aug 19 08:48:48 glue systemd[1]: glue.service: Main process exited, code=exited, status=134/n/a
Aug 19 08:48:48 glue systemd[1]: glue.service: Failed with result 'exit-code'.
Aug 19 08:48:48 glue systemd[1]: glue.service: Consumed 2min 45.458s CPU time.
```

Unfortunately, there's no strack trace and it also does not appear in Sentry, so I guess the complete process crashes somehow.

Now to my question: What libraries with native dependencies are you using which could cause that? Are you aware of any ways to debug this?

Thanks!

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by Julusian** [comment]
The only one I am aware of is https://github.com/julusian/node-freetype2. 
Could you make a minimal reproduction with either that lib directly or this, so that I can debug through it to see what is happening?

**Comment by hrueger** [comment]
Sure, I'll try to.

**Comment by hrueger** [comment]
Hm, it looks like this is quite complicated to reproduce in a standalone project. Maybe there are several factors, or it it not that library. I'll keep thinking and trying.

**Comment by Julusian** [comment]
We use the native library for drawing multiviewer labels, for models released before the atem mini range.
Maybe it is needed to do something with drawing a label to trigger it?

**Comment by hrueger** [comment]
I don't think so, it crashes before even connecting. I don't need an ATEM to make it crash, I just need to import and create the instance.

**Comment by Julusian** [comment]
Is this still a problem?
Without a way to reproduce this, I don't know where to begin trying to figure out the cause

**Comment by hrueger** [comment]
Hi, I'm not sure. I'm no longer working for that client. Feel free to close 👍
