### ISSUE TITLE
Other:  Vite React: Uncaught ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by AronBuzogany** [Sofie-Automation/sofie-atem-connection#168]
### About me

Working on a React app to control my Atem

### Issue

When importing

```js
import { Atem } from "atem-connection";
```

I get the following error:

```
Uncaught ReferenceError: __dirname is not defined
```

I am using Vite + React

**Comment by nytamin** [comment]
The mos-connection library is a node.js only application, it will not work in a browser.

**Comment by nytamin** [comment]
atem-connection is a node.js only library, it will not work in a browser.
