### ISSUE TITLE
Connection logic acking problems

### ISSUE THREAD

**Issue by Julusian** [Sofie-Automation/sofie-atem-connection#28]
* **I'm submitting a ...**
[*] bug report

* **Summary**

https://github.com/nrkno/tv-automation-atem-connection/blob/fd3d045f8c2fcfb4ba4e12179ac50b3305f242b6/src/lib/atemSocketChild.ts#L157-L160
This acking strategy is dodgey. When you ack a packet, you are also acking any previous packets, meaning that if we dont get #101, but send an ack for #102, the atem thinks we received #101.
Something worth noting is that the atem appears to send acks on a timer instead of immediately, sending an ack for at most 16 packets at a time, with a max delay of a few ms. This could be good to do as a later perf improvement, as it will reduce the number of packets we need to send when receving a lot at once.
Depending on how the atem handles acks internally, it could also cause some confusion if we ack #102 then #101, as it is possible it could resend #102, although I am not sure if that happens or would be a problem for us.

The strategy I am using is to track the last packet, and if the received id is not the next number, then I discard it (knowing that id will be retransmitted) and I will batch the acking by the same rules as the atem uses.

https://github.com/nrkno/tv-automation-atem-connection/blob/fd3d045f8c2fcfb4ba4e12179ac50b3305f242b6/src/lib/atemSocketChild.ts#L192-L214

This retransmit strategy doesnt appear to work. (this looks to be new in feature/upload and 0.6.0 looks fine, so probably just needs a revert)
As far as I am aware, if the atem doesn't ack a packet, then it needs to be retransmitted with the same id (along with anything sent after it?). If the sequence it receives skips a number it will wait for that missing one to be received before continuing.
https://github.com/Julusian/tv-automation-atem-connection/commit/c8caeaa81783b95ef471e5650f7571486192b561
A crude example for simulating a packet drop by making the sending code skip an id. It gets stuck trying to resend the last command, until it times out. And the command is never processed by the atem.

**Comment by mint-dewit** [comment]
Cool, this is a really detailed and useful post for me! Thanks for the write up.

**Comment by mint-dewit** [comment]
> This acking strategy is dodgey. When you ack a packet, you are also acking any previous packets, meaning that if we dont get #101, but send an ack for #102, the atem thinks we received #101.

Definitely, this should be fixed by https://github.com/nrkno/tv-automation-atem-connection/commit/bfb679f3e1f77372c00824f0cfac6f8fe71173f2

> Something worth noting is that the atem appears to send acks on a timer instead of immediately, sending an ack for at most 16 packets at a time, with a max delay of a few ms.

I tried to implement this, but found that this is too slow using default NodeJS timers. We would have to look into higher precision timers (or other optimizations?)

> This retransmit strategy doesnt appear to work. 

Reverted in https://github.com/nrkno/tv-automation-atem-connection/commit/2fe636817bcdb6d7f5d0dc5353e2a2466a69a8d8

> (along with anything sent after it?).

Implemented as well, it seems to like it.

**Comment by mint-dewit** [comment]
As far as I can see all parts of this issue have been fixed now. Please reopen / open a new issue if something comes up.
