### ISSUE TITLE
Timers are not always stopped on disconnect()

### ISSUE THREAD

**Issue by haakonnessjoen** [Sofie-Automation/sofie-atem-connection#38]
https://github.com/nrkno/tv-automation-atem-connection/blob/f35250d6eb46287d3295c27a772b4a8c17c09181/src/lib/atemSocketChild.ts#L74

(In disconnect) The timers should be stopped even if the connection has not been established. The clearing of timers should be moved to above the "```if (this._connectionState === ConnectionState.Established)```" check. ( or in the else if you want :P )

If I run disconnect() on the instance that has not connected, because I am going to delete the instance, there will be freerunning timers that I have no way to stop.

**Comment by mint-dewit** [comment]
Let's not _move_ them in to the else, because then we would not clear them out when we did establish a connection ;)

**Comment by haakonnessjoen** [comment]
haha, yes. copy to the else :P
