### ISSUE TITLE
Fade to Black function missing?

### ISSUE THREAD

**Issue by nickehallgren** [Sofie-Automation/sofie-atem-connection#50]
* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

Hi,

I've been playing around with atem-connection and it works perfectly on the old ATEM 2 M/E Production Switcher. But I can't find anything about FTB, I found followFadetoBlack under AudioMixerMasterCommand or is it hidden somewhere? It would be nice to be able to check if FTB is on and to enable/disable it...

Thanks in advance!

Best regards
Nicke

**Comment by mint-dewit** [comment]
Hi Nicke,

Good to hear the library is working well for you, I've added support for controlling FadeToBlack controls in the /develop branch just now. It will be included in the next release of the library!

**Comment by Julusian** [comment]
This should be resolved in v1.0.0 of the library which has just been released
