### ISSUE TITLE
v8/Constellation Support

### ISSUE THREAD

**Issue by krocheck** [Sofie-Automation/sofie-atem-connection#51]
I am currently working on this.  Not sure if anyone else is, so I'd like to be careful about doubling up.  There is some discussion in the #blackmagic Slack channel for Companion.

We can use this as an open discussion as well since I'm not going to drop a PR until I work through everything.

Currently major changes in the protocol are for SuperSource, which is to be expected since the new switcher supports two.  The byte shifts are not awful and adding `ssrcId = 0` as a parameter to existing calls seems ok.  The main concern is that SSrc/CSSc has been split where SSrc maintains the existing structure (with ssrcId added) but all border related properties have moved to SSBd/CSBd.  This would appear to break `setSuperSourceProperties(..)` as any calls to that for border properties would move to `setSuperSourceBorder(..)`.  Or there may be some trickery I'm not seeing to not break that.

Open question is how to handle a release for v8 since there would be an expectation that all users of downstream software need to update their switchers to v8 to maintain compatibility.  For me, if it weren't for us buying a Constellation all of our switchers would remain on v7.5.2 for some time until a v8.0.x were to come out.  Certainly downstream software can elect to wait for a period to add this support regardless of a release adding it.  Not sure if there should be a branch for a period to allow bug fixes for v7.5.2?

WIP code is visible in this repo: https://github.com/krocheck/internal-dev/tree/master/_node_/atem-connection/src

**Comment by mint-dewit** [comment]
First of all, thanks for the reverse engineering of that stuff! We know it's non-trivial and BMD doesn't make it very easy.

Officially we've only ever supported firmware version 7.2, although seemingly all 7.x versions seem to run pretty well with our library. The main reason we never upgrade is that we have no automated testing in place, so we need to find changes in the protocol by trial and error. We have some new ideas regarding this and consider it a first step towards upgrading our switchers.

Even then, we don't want to make a hard switch to v8.x of the protocol. As you noted, it's important to leave room for 7.x bug fixes and give developers and users time to upgrade. This implies we want to support multiple protocols in one release of the library. We'll need some extra structures for this though, and I'm hoping to add those this week then you can freely base a PR on that and we'll be happy to merge!

**Comment by krocheck** [comment]
@baltedewit worst case, Companion can live off its own fork for a period until the project wants to roll this in.  But yeah, let me know when the version detection mitigation is in and I can program around that.

**Comment by Julusian** [comment]
I would expect that Companion would like to have version detection in place. I find it isn't always possible to update the atem firmware when it is borrowed or hired, so if companion requires v8 that will be problematic.
But overall there are very few breaking changes in v8 so it wont be that bad to support both

**Comment by mint-dewit** [comment]
I have now pushed a `feature/v8` branch that contains my first ideas of how multi-version support could/should work.

In essence you either do or do not define a version property on the command class. If you don't it implies it is a baseline command, baseline commands are all the commands we have now. e.g. commands that work on 7.x. If you do define a version that implies that command can only  be used with a firmware of that version or higher.

The MultiViewerSource command is an example of how this could look (a deprecated 7X class, different State objects and an if-statement in the high level method), a git diff of the changes can be found via [this commit](https://github.com/nrkno/tv-automation-atem-connection/commit/e52fd4e0f9166b6abe68c38170c9df74d4b0c566)

**Comment by mint-dewit** [comment]
We have merged this into `/develop` now but we would love some testing before we do a full release. The API has remained reasonably similar with a few exceptions:

- The supersource methods have been split up
- The state object has changed in order to reflect the supersource changes
- The stateChanged event no longer carries the command instance and instead carries the address of the changes inside the state

**Comment by krocheck** [comment]
I'll begin working this through and see what happens.  Thanks!

**Comment by Julusian** [comment]
v1.0.0 has been released with support for v8.0 and v8.0.1.
As far as I am aware it should support everything needed for the Constellation, but if we missed something then open another issue
