### ISSUE TITLE
Updating input name doesn't update multiviewer

### ISSUE THREAD

**Issue by Julusian** [Sofie-Automation/sofie-atem-connection#59]
**I'm submitting a ...**
[*] bug report

**Affected**
Constellation in v8.0.2
TV Studio HD in v7.5.2
2ME in v8.0.2

**Unaffected**
Atem Mini Pro ISO v8.6.4
Atem Mini Extreme ISO v8.6.4
(It is assumed that all of the mini range are unaffected by this)

**Summary**
Using `setInputSettings` to set the longName of a source does not update the multiviewer.
Other connected clients picks up the new device name, so the set command does work successfully. But atem client is sending an encoded image with the new name, which we are not doing.

**Notes**
It is the same process as a stills upload, with the following differences:
storeId = 0xffff
mode (TransferMode) = 0x0201
transferIndex = sourceId
filename = 'Label'
description = ''
hash = 0x00

The image appears to be 8bit per pixel, with some unknown encoding. Viewing in greyscale looks weird, but is recognisable.
RLE encoding can be used during the upload.
For one model, the image is 640 x 190, and contains a render for each of 4k?, 1080, and 720. But this varies based on device capabilities.

**WARNING**
We found that sending images with a full gradient of grey would crash the ATEM, so this needs extensive testing to ensure that our implementation is safe.

**Other information**
Wireshark of example [atem-set-source-name-does-upload.zip](https://github.com/nrkno/tv-automation-atem-connection/files/3653143/atem-set-source-name-does-upload.zip)
Image extracted from wireshark capture: [ripped-from-wireshark.zip](https://github.com/nrkno/tv-automation-atem-connection/files/3653190/ripped-from-wireshark.zip)

**Comment by mint-dewit** [comment]
The 8.2.2 updates list "Improved graphics quality in multiview display." as part of the changelog. It might have changed parts of what is described in the original issue (hopefully for the better?)

**Comment by Julusian** [comment]
Looking at what got a firmware update, that must be referring specifically to the mini pro. So I really hope they havent changed how the images are encoded

**Comment by mint-dewit** [comment]
I guess it's not unlikely it's just improvements for the Mini Pro
