### ISSUE TITLE
_sentQueue leaks

### ISSUE THREAD

**Issue by Julusian** [Sofie-Automation/sofie-atem-connection#63]
* **I'm submitting a ...**
[*] bug report

* **Summary**
https://github.com/nrkno/tv-automation-atem-connection/blob/master/src/atem.ts#L103

When we call `sendCommand(...)`, we internally track the command in `_sentQueue`.
If the call to `this.socket._sendCommand(...)` fails, then we reject the promise, but don't remove the command from `_sentQueue`, and so will leak some commands.
Additionally, if the atem disconnects before a command is acked, I think we wont resolve or reject the promises remaining in `_sentQueue`, again leaking them and leading to unresolved promises which could cause logic errors in library consumers.

* **Other information**
This is all theoretical, none of these thoughts have been tested yet.

**Comment by mint-dewit** [comment]
Disconnect before ack implies we will timeout in the socket class, thus rejecting the promise (I think)

Rejecting any sent commands should definitely remove them from the queue though.

**Comment by Julusian** [comment]
> Disconnect before ack implies we will timeout in the socket class, thus rejecting the promise (I think)

Going deeper that raises more concerns. Such as retransmits continuing across calls to connect/disconnect.

Ill try and find some time to confirm this, and look at writing some tests for the packet sending/handling logic
