### ISSUE TITLE
The socket process unexpectedly closed

### ISSUE THREAD

**Issue by ronag** [Sofie-Automation/sofie-atem-connection#65]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

Child process keeps dying and spamming errors

Node v12.9.1
OS: MacOS
ATEM: 8.0.3

I get this error spammed into the console. Unfortunately no further info.

```
    err: {
      "type": "Error",
      "message": "The socket process unexpectedly closed (code: \"1\", signal: \"null\")",
      "stack":
          Error: The socket process unexpectedly closed (code: "1", signal: "null")
              at /Users/ronagy/GitHub/nxtedition/nxt/event/node_modules/atem-connection/dist/lib/atemSocket.js:102:36
              at processTicksAndRejections (internal/process/task_queues.js:75:11)
    }
```

Q: Why is a child process used here?

**Comment by Lange** [comment]
Hi, thanks for this report. What model of ATEM are you using, and what
software version is it running on?

**Comment by ronag** [comment]
I have no idea how to check. I've got ATEM Software Control but it doesn't seem to want to tell me the secret.

**Comment by ronag** [comment]
Ah! I enabled debug and now I get a `ENOTFOUND`. Should probably be handled a bit more gracefully.

**Comment by Julusian** [comment]
> Q: Why is a child process used here?

The atem requires pings to be responded to within a few hundred ms or it drops the connection. We were finding that this would sometimes randomly happen when the main thread got busy #19

**Comment by ronag** [comment]
Cool thanks. The invalid address handling could probably be a bit more graceful but I'm all good.

Once I get time I'll probably to a PR to improve it.

Great lib!
