### ISSUE TITLE
Support for the ATEM Mini

### ISSUE THREAD

**Issue by ghost** [Sofie-Automation/sofie-atem-connection#71]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Hi there - just wondering if the library does / will support the ATEM Mini?

**Comment by mint-dewit** [comment]
We don't officially support specific models, that being said... basic functionality should work just fine out of the box.

**Comment by ghost** [comment]
@baltedewit Thanks for the reply - I suspected as much, but when I hooked up to our first Mini today the connection just sat in a "reconnect" cycle. Is there anything I can do to contribute to the library, given that I have a physical device available?

**Comment by mint-dewit** [comment]
@Julusian has one to develop against, so nothing we need there.

Did you connect via USB or network? USB is not and will not be supported.

**Comment by ghost** [comment]
@baltedewit Sounds good. I initially connected via USB to set the IP etc, but used the ethernet port once the LAN settings were correct. I will run a couple more tests for now and will keep an eye on the library to see if there are any specific updates to support this device. Thanks again!

**Comment by Julusian** [comment]
I believe this library should just work with the mini. I think I have tried the basics with my mini, and in everything else I tried with another library did not find anything broken so everything should work.
It will not work over usb though.

**Comment by ghost** [comment]
@Julusian OK, sounds good to me. We're definitely using ethernet, so I'll check my plugin code and make sure I've definitely got comms with the Mini. Appreciate the quick response.
