### ISSUE TITLE
preview / program tally info during transitions

### ISSUE THREAD

**Issue by PeterMaes** [Sofie-Automation/sofie-atem-connection#77]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

* **Summary**
I am trying to get the real tally info of this module, but could not find the right info so far.
During transitions the tally info is showing a red indication on the Preview button (in Atem Software Control).
I am using state.video.ME[0].programInput and state.video.ME[0].previewInput to get program and preview state. But during transition these values do not represent the right info.
Below the info I have logged (timestamp in front)
Immediatly after sending the AutoTransition action I got an event that repeats the previewInput state. To me it seems this is wrong, but maybe I am missing some details here.

1586875643417 state.video.ME[0].programInput= 2
1586875643419 state.video.ME[0].previewInput= 1
1586875652282 KeyPress= AUTO/CUT
1586875652322 state.video.ME[0].previewInput= 1
--- transitions is happening here ---
1586875654302 state.video.ME[0].programInput= 1
1586875654303 state.video.ME[0].previewInput= 2

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by Julusian** [comment]
The events being emitted here are a direct representation of what the atem is sending to the library. The preview & program inputs get swapped at the very end of the transition (you can prove this by hot cutting preview and program during a running transition). Atem Software Control must be changing the colour when it knows that it is in a transition (another property we have defined somewhere)

Perhaps you are after the listVisibleInputs function? https://nrkno.github.io/tv-automation-atem-connection/globals.html#listvisibleinputs This is designed to give the same preview & program state as seen on the multiviewer, and handles transitions, keyers and supersources.

**Comment by PeterMaes** [comment]
Thanks for your quick and helpfull reply.
Indeed this is the function I was looking for !

**Comment by mint-dewit** [comment]
> Atem Software Control must be changing the colour when it knows that it is in a transition

`state.video.ME[0].inTransition` (works for both auto transition and manually running the t-bar)
