### ISSUE TITLE
unexpected states when parsing information for tally lights

### ISSUE THREAD

**Issue by lukas-runge** [Sofie-Automation/sofie-atem-connection#81]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

* **Summary**
I am building a **dmx tally light solution** for atem switchers. When I just cut between two cameras there is one state transmitted which has previous preview as program so preview and program are identical for one state. This results in the previous program tally switching off before switching to green again. (flickering)
In this example I am only showing camera 1 tally information to make it easier to understand:
![image](https://user-images.githubusercontent.com/21328241/81232183-b6ce7f80-8ff4-11ea-93f6-4fd9b28fbdbf.png)

**Is there any way to catch this case or directly extract tally light information for example for one input with the atem-connection library?**

**Thank you** all in advance **for** your help and **this awesome open source library!**
Kind regards
@lukas-runge 

* **Other information**
To get the Tally light information I am parsing the state object to extract tally information out of it. (using `listVisibleInputs()` on the switcher object) and some ways to prevent weird states messing up my readout.

**Here is my current code** 🔽 
![parseForTally](https://user-images.githubusercontent.com/21328241/81232042-7969f200-8ff4-11ea-8c3a-d3566a43a3ff.png)
*image created with [Polacode](https://marketplace.visualstudio.com/items?itemName=pnp.polacode) for [Visual Studio Code](https://code.visualstudio.com/)*

<details>
<summary><b>copy/paste code</b></summary>

```Typescript
this.switcher.on('stateChanged', (state: any) => {
    // State does not always contain ME video data; Return if necessary data is missing.
    if(!state || !state.video || !state.video.ME || !state.video.ME[0])
        return;
    
    // There is some weird state change after a transition that I am able to catch with my glitch variable here
    if (state.video.ME[0].inTransition) {
        state.video.ME[0].transitionPosition == 0 || state.video.ME[0].transitionPosition == 10000 ? glitch = true : null;
    } else {
        glitch = false;
    }
    
    // checking out current preview and program information
    let new_preview = this.switcher.listVisibleInputs("preview", 0)
    let new_program = this.switcher.listVisibleInputs("program", 0)

    // comparing to old preview information, updating if changed
    if (_.isEqual(this.preview, new_preview) == false && glitch == false) {
        console.log(`PREVIEW: ${new_preview}`)
        this.preview = new_preview
        update_now = true
    }

    // comparing to old program information, updating if changed
    if (_.isEqual(this.program, new_program) == false && glitch == false) {
        console.log(`PROGRAM: ${new_program}`)
        this.program = new_program
        update_now = true
    }

    // notifing tallys ("Inputs") if there are changes
    if (update_now == true) {
        this.notifyInputs();
        update_now = false
    } 
});
```

</details>

**Comment by Julusian** [comment]
I think this is a known limitation of the v1 releases. The way we parse commands from the atem means that we emit a stateChanged for every single thing it sends, even thought they are batched. This will be better in v2, but there are some bugs there that are blocking its release (eg #76)

As a workaround, you could try adding a simple debounce to stateChanged, so that you wait for a gap in commands before doing this, but I dont know if that will play well with transitions..
I dont have any better ideas right now, not without modifying the library to expose some more data

**Comment by lukas-runge** [comment]
Hi @Julusian,

**thank you for your ultra fast response.**
Your idea sounds like a solution that would work for me. I should be able to catch the case in which i am dealing with a transition to only apply the function in the other cases. 👌 I am not that experienced in coding tho, so i'll have to first learn how to write a debounce function in typescript. But I'll try to do my best. Thank you very much for your assessment on my challenge.
Other than that: When do you think we can expect v2?

Kind regards
@lukas-runge

**Comment by Julusian** [comment]
There is no concrete timescale on v2. It is waiting for either me to have the time and motivation to look into the issues which were reported, or for nrk to want to upgrade to it and provide the time needed.

It does mostly work, I think it is just some bugs in edge case conditions, or functionality used less often

**Comment by lukas-runge** [comment]
Appreciate the work and time you guys are putting into this. **Thank you very much!** I would love to test v2 to see if it works without issues in my usecase. So I could just clone the current state of the master branch, build it and copy it into the node_modules folder to test v2 myself, right?

Kind regards
@lukas-runge

**Comment by Julusian** [comment]
The easiest way to install it is via `npm install atem-connection@nightly`
There are some small api differences, but as you are using typescript, it should report anything

**Comment by lukas-runge** [comment]
**Awesome!** Just tried it with the nightly build. Works like a charm in my usecase 😎 Even enabled me to make my code much simpler cuz' all of the weired in between states are gone now 😍👌
![image](https://user-images.githubusercontent.com/21328241/81288105-43645680-9064-11ea-840c-10040613e835.png)

Thank you @Julusian your fast help on my challenge and huge thanks to all maintainers of this library for enabling me to do my project at all - **thank you guys!**

Kind regards
@lukas-runge 

**Here is my new code** 🔽 
![nightly-test-2](https://user-images.githubusercontent.com/21328241/81289304-7b6c9900-9066-11ea-9059-5d739a6394f8.png)
*image created with [Polacode](https://marketplace.visualstudio.com/items?itemName=pnp.polacode) for [Visual Studio Code](https://code.visualstudio.com/)*

<details>
<summary><b>copy/paste code</b></summary>

```Typescript
constructor (ip: string) {
    this.ip = ip
    this.switcher = new AtemSwitcher()

    this.switcher.on('connected', (state: any) => {
        console.log(`Connected to ${this.ip}.`);

        let update_now: boolean = true;
        update_now = this.parseNewState(update_now)

        this.switcher.on('stateChanged', (state: any) => {
            update_now = this.parseNewState(update_now)
        });

    })

    this.switcher.on('disconnected', () => {
        console.log(`Disconnected from ${this.ip}.`);
        this.connect();
    })

}

parseNewState(update_now: boolean):boolean {
    
    // checking out current preview and program information
    let new_preview = this.switcher.listVisibleInputs("preview", 0)
    let new_program = this.switcher.listVisibleInputs("program", 0)
    
    // comparing to old preview information, updating if changed
    if (_.isEqual(this.preview, new_preview) == false) {
        console.log(`PREVIEW: ${new_preview}`)
        this.preview = new_preview
        update_now = true
    }

    // comparing to old program information, updating if changed
    if (_.isEqual(this.program, new_program) == false) {
        console.log(`PROGRAM: ${new_program}`)
        this.program = new_program
        update_now = true
    }

    // notifing tallys ("Inputs") if there are changes
    if (update_now == true) {
        this.notifyInputs();
        update_now = false
    }

    // return update_now: boolean to track if
    // information has changed compared to previous state
    return update_now
}

connect () {
    console.log(`Connecting to ${this.ip}...`);
    this.switcher.connect(this.ip)
}
```

</details>

**Comment by lukas-runge** [comment]
Hi everyone,

finally finished & published my **tally light** tool 🎉

Thank you @Julusian for your fast help on during development and huge thanks to all maintainers of this library for enabling me to do my project at all - **thank you guys!**

Now I am very excited to see how people are going to use my new **atem-tools** library:
https://www.npmjs.com/package/atem-tools

Kind regards
@lukas-runge
