### ISSUE TITLE
Repeated missed ping reconnections with no apparent lack of functionality

### ISSUE THREAD

**Issue by markschwartzkopf** [Sofie-Automation/sofie-atem-connection#82]
* **I'm submitting a ...**
[x] bug report?

* **Summary**

version: 2.0.0-nightly-20200117-174823-3f8cfe7.0
I'm intermittently getting infinitely repeated "child missed 3 pings, exiting process!" followed by reconnection notices. All commands sent still seem to work and state updates received seem to be still be correct. I have had some unexplained things happen that could have been caused by incorrect state information, but every time I've checked, it's been correct.

Possibly related to https://github.com/nrkno/tv-automation-atem-connection/issues/76

**Comment by Julusian** [comment]
what model atem are you using this with?
can you provide rough spec of your cpu? is the machine doing much else?

my first thought is that yeah #76 could be related, as well as #75.

**Comment by markschwartzkopf** [comment]
ATEM: Television Studio HD
CPU: Ryzen 5 1600 Six-Core, 3.2 GHz
It's also running OBS and NodeCG. Pretty much just two inputs into OBS, though, the ATEM and the NodeCG overlay.

**Comment by Julusian** [comment]
Is the node application that you are running the atem-connection in doing much else?
I can reproduce this by doing a load of `fs.readFileSync` to block node for a few seconds.

I shall look into whether we can improve the case here of where node does block. As that shouldnt be treated as the child not responding

**Comment by Julusian** [comment]
This is waiting on me to finish up https://github.com/nytamin/threadedClass/pull/33 which should resolve this

**Comment by Julusian** [comment]
This should be resolved in `2.0.0-nightly-20200626-195656-eb05a5c.0`
