### ISSUE TITLE
Add support for ATEM Mini Pro

### ISSUE THREAD

**Issue by GarthDB** [Sofie-Automation/sofie-atem-connection#83]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] question about the decisions made in the repository
  - [ ] question about how to use this project

* **Summary**
I'm using my ATEM Mini Pro with my Bitfocus Companion that uses this project.

If it's possible to control the new functionality would be nice, but at least controlling the Pro like the ATEM Mini would be a great start.

**Comment by Julusian** [comment]
In companion it will work fine to force it to be treated as a normal mini. So this has been low on my todo list, but I shall get it done

**Comment by Julusian** [comment]
v1.3.1 and master both have this
Working on pulling into companion now
