### ISSUE TITLE
Multiview weirdness

### ISSUE THREAD

**Issue by markschwartzkopf** [Sofie-Automation/sofie-atem-connection#84]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[*] question about how to use this project

* **Summary**
I'm changing an input's longName with `myAtem.setInputSettings({longName: 'hey'}, 2)`
This is functional, but does not propagate to the multiview labels. How is that meant to be done?

**Comment by Julusian** [comment]
Dupliate of: #59 
This is a known issue, and not something that is supported yet.
This is because it will require us to render the text as an image with some special encoding and upload it to the atem.
It is something we hope to do, but there is no timeframe as it is quite a lot of work
