### ISSUE TITLE
listVisibleInputs, fail when supersource nested with MEs

### ISSUE THREAD

**Issue by thormug** [Sofie-Automation/sofie-atem-connection#86]
Hi,

listVisibleInputs is not working properly when MEs and supersource are nested.

For example :

You have SuperSource on your ME1
You have Input 1 on your ME2
In Box1 of your supersource, you have ME2

listVisibleInputs does not return input1, but it should.

Thank you very much !

**Comment by Julusian** [comment]
Thanks for reporting this, that was a good spot.
I have pushed a fix which is in the v1.3.2 release
