### ISSUE TITLE
listVisibleInputs crash when supersource active during connection

### ISSUE THREAD

**Issue by thormug** [Sofie-Automation/sofie-atem-connection#87]
Hi,

When you start a connection with an atem which have a supersource active and immediatly do a listVisibleInputs, Supersources Objects are not populated and the function listVisibleInput do crash

```
TypeError: Cannot read property 'artFillSource' of undefined
         at Object.listVisibleInputs (atem-connection/dist/lib/tally.js:42:48)
```

Steps to reproduce :

Put Supersource in ME1
```
atemclient.on('stateChanged', function(err, state) {
	console.log(atemclient.listVisibleInputs("program"))
});
```
Establish a connection with the atem.

Suggestion : 
Check if supersource is populated during listVisibleInputs

**atem-connection/dist/lib/tally.js** at line 36, ssrc can return : 
`SuperSource { boxes: {}, index: 0 }`

We need to check the existence of ssrc.properties before moving on.

Thank you very much !

**Comment by Julusian** [comment]
Thanks for this. Annoyingly this is something that has already been fixed in the upcoming v2.0, but that needs a bit more testing before I can release it..

v1.3.3 is now published which will resolve this
