### ISSUE TITLE
Incompatible videoMode on AMP 8.2.3

### ISSUE THREAD

**Issue by astellingwerf** [Sofie-Automation/sofie-atem-connection#88]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
I'm running a Atem Mini Pro. It is updated to 8.2.3. Its `videoMode` (`this.state.settings.videoMode`) is set to `27`, while `atemUtil_1.Util.getResolution` only has an array of 20 elements. As a result, I am unable to upload stills.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
The array in [atemUtil.ts](https://github.com/nrkno/tv-automation-atem-connection/blob/master/src/lib/atemUtil.ts#L95) should probably be extended to fix this.

These are the modes I was able to identify with my AMP:
- 8: 1080p23.98
- 9: 1080p24
- 10: 1080p25
- 11: 1080p29.97
- 12: 1080p50
- 13: 1080p59.94
- 26: 1080p30
- 27: 1080p60

**Comment by Julusian** [comment]
The missing videomodes have been added in 543ef69173dae0696f2245a00f23f40d9f40dbdb https://www.npmjs.com/package/atem-connection/v/2.0.0-nightly-20200730-203236-543ef69.0
