### ISSUE TITLE
MSRc Macro Start Recording

### ISSUE THREAD

**Issue by filiphanes** [Sofie-Automation/sofie-atem-connection#90]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Please implement command for Macro Start Recording

**Comment by Julusian** [comment]
This is implemented in the next v2 prerelease d9d9a3f6a461e3b970332b9265d72fd3da5be467
