### ISSUE TITLE
CMPr, MRCP Macro Change Properties

### ISSUE THREAD

**Issue by filiphanes** [Sofie-Automation/sofie-atem-connection#91]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
 Please implement command for Macro Run Change Properties for looping setting

**Comment by Julusian** [comment]
These are implemented in 2.0.0-nightly-20200807-162305-33a3da4.0
