### ISSUE TITLE
AudioMixerInput/-Master not working

### ISSUE THREAD

**Issue by jSebestyen590** [Sofie-Automation/sofie-atem-connection#93]
* **I'm submitting a ...**
[x?] bug report
[ ] feature request
[x] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Im playing around with an ATEM Mini (Firmware: 8.2.3). Both AudioMixerInput- and AudioMixerMasterCommand do not work as expected (i.e. nothing noticably changes, ATEM does not send any response).
I've been playing around with the CFSP command to send audio options successfully and FASP command to receive them successfully as well. One thing I stumbled upon is the `AudioMixOption`-enum which maps off to 0, on to 1 and afv to 2.
As far as I was able to reverse-engineer said commands I found that off equals 1, on equals 2 and afv equals 4.

Does the API use different mappings for the same keys, are AudioMixerInputCommands restricted to other ATEM devices or are the existing commands deprecated?

**Comment by Julusian** [comment]
The existing commands are correct for anything which does not include Fairlight audio (tvshd was the last to use the classic audio)
Newer models are all Fairlight based which this library does not yet have any support for.

I did start working on this the other day, but didn't get far enough for anything useful, and was having problems with some ids as they don't encode to Json cleanly (I have a plan for it now) 
I already have all the commands figured out and documented and I hope to spend some more time on it this week.

**Comment by jSebestyen590** [comment]
That's good to hear!
Let me know if I can assist you in any way :)

**Comment by thebluetiger** [comment]
I have an ATEM Constellation 8K - how can I help?

**Comment by Julusian** [comment]
The latest 2.1.0 prereleases have new methods to control fairlight audio

**Comment by kellertobias** [comment]
So how does one change the master level or any input level with the new methods for fairlight audio?

**Comment by Julusian** [comment]
input level can be done with `setFairlightAudioMixerSourceProps(index, source, { faderGain: -2 })`
I appear to have missed the part of this asking for control of master properties

**Comment by kellertobias** [comment]
@Julusian what is the "source" supposed to be? The value I passed in here (-65280), taken from `Object.keys(myAtem.state.fairlight.inputs.1.sources)[0]` seems a bit arbitrary. Do these values depend on device or when do they change?
