### ISSUE TITLE
Set Flying Key Position

### ISSUE THREAD

**Issue by kellertobias** [Sofie-Automation/sofie-atem-connection#97]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository
[X] question about how to use this project

* **Summary**
I am trying to find a way to set the X/Y position and scale of a Upstream Flying Key, however I cannot find which Command to use for it.

**Comment by Julusian** [comment]
I think that falls under MixEffectKeyDVECommand/setUpstreamKeyerDVESettings()
Its not the most clear, because we are matching what the atem does internally here..

**Comment by endreszabo** [comment]
This works for me:

```
atem.setUpstreamKeyerDVESettings({"sizeX":900});
```
