### ISSUE TITLE
Why does pathToChange in stateChaged not correspond to object?

### ISSUE THREAD

**Issue by br8kpoint** [Sofie-Automation/sofie-atem-connection#98]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ x] question about the decisions made in the repository
[x ] question about how to use this project

* **Summary**

When the state changed event is fired, the pathtoChanged array does not contain valid paths into the object. Should you not be able to do state[pathToChanged] to get the value of what has changed?

Why is it video.ME.0.programInput?

Is there a function that will translate the path into the actual value / object that was changed?

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by Julusian** [comment]
There is a bug here. It is supposed to be `video.mixEffects.0.programInput` not `video.ME.0.programInput`. The paths changed in 2.0 and some cases were not updated. A fix has been written and will be in the next version, but it hasnt been released yet.

It it supposed to be that the paths will work with https://www.npmjs.com/package/object-path to get the changed object. And either regex or some other string operations to figure out exactly what changed

**Comment by br8kpoint** [comment]
Thanks. I'll look into object path. Is there a pull or branch with the fix?

**Comment by Julusian** [comment]
Yes, it is in master and as a prerelease on npm as `2.1.1-nightly-20200917-210751-66bb5be.0`

**Comment by Julusian** [comment]
This has been published in v2.2.2
